

return _G.ConstClass("WorldConfig",{
    [1] = { sid = 1, path = "Scene/Zhucheng_southeast_corner/prefabs/Zhucheng_southeast_corner", name = "测试场景", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [2] = { sid = 2, path = "Scene/Zhucheng_southeast_corner/prefabs/Zhucheng_southeast_corner", name = "测试场景", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [3] = { sid = 3, path = "Scene/Battle_Streetscape/prefabs/Battle_Streetscape", name = "创建角色", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10] = { sid = 10, path = "Scene/Zhucheng_southeast_corner/prefabs/Zhucheng_southeast_corner", name = "测试场景", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [11] = { sid = 11, path = "Scene/Zhucheng_southeast_corner/prefabs/Zhucheng_southeast_corner", name = "测试场景", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [12] = { sid = 12, path = "Scene/Zhucheng_southeast_corner/prefabs/Zhucheng_southeast_corner", name = "测试场景1", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [21] = { sid = 21, path = "Scene/Zhucheng_southeast_corner/prefabs/Zhucheng_southeast_corner", name = "测试关卡场景区域1", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [9002] = { sid = 9002, path = "Scene/Jianghu/prefabs/Jianghu", name = "两只怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [9001] = { sid = 9001, path = "Scene/Battle_Streetscape/prefabs/Battle_Streetscape", name = "一只怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [9003] = { sid = 9003, path = "Scene/Battle_Streetscape/prefabs/Battle_Streetscape", name = "三只怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10001] = { sid = 10001, path = "Scene/Jisitading/prefabs/Jisitading", name = "吉斯塔顶部", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10002] = { sid = 10002, path = "Scene/Nanzhendongqu/prefabs/nanzhendongquzhuzhaiqu_01", name = "东区住宅区", items = { 1000209001, 101 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10003] = { sid = 10003, path = "Scene/Nanzhendongquguangchang/prefabs/Shangyeguangchang", name = "东区广场", items = { 1000309101, 102 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10004] = { sid = 10004, path = "Scene/Zhucheng_southeast_corner/prefabs/Zhucheng_southeast_corner", name = "东区中央城", items = { 1000409001, 1000409002, 1000409003, 1000409004 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10005] = { sid = 10005, path = "Scene/Jianghu/prefabs/Jianghu", name = "交错之门", items = { 1000509001 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10006] = { sid = 10006, path = "Scene/Jianghu/prefabs/Jianghu", name = "镇元斋道场", items = { 1000609001 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10007] = { sid = 10007, path = "Scene/Zhucheng_southeast_corner/prefabs/Zhucheng_southeast_corner", name = "佣兵组织基地", items = { 1000709001, 1000709002 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10008] = { sid = 10008, path = "Scene/Battle_Streetscape/prefabs/Battle_Streetscape", name = "佣兵组织基地废墟", items = { 1000809001 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10009] = { sid = 10009, path = "Scene/Jianghu/prefabs/Jianghu", name = "安全屋", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10010] = { sid = 10010, path = "Scene/Nanzhendongqushuniu/prefabs/Nanzhendongqushuniu", name = "东区枢纽", items = { 1001009001, 1001009002, 1001009003 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10011] = { sid = 10011, path = "Scene/Nanzhendongqujiaowai/prefabs/Nanzhendongqujiaowai", name = "东区郊外", items = { 1001109001, 103 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10012] = { sid = 10012, path = "Scene/Senlin/prefabs/Senlin", name = "北区东海岸", items = { 1001209001, 1001209002 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10013] = { sid = 10013, path = "Scene/Zhucheng_southeast_corner/prefabs/Zhucheng_southeast_corner", name = "北区中央城", items = { 1001309001, 1001309002, 1001309003 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10014] = { sid = 10014, path = "Scene/Nanzhendongquguangchang/prefabs/Shangyeguangchang", name = "北区广场", items = { 1001409001, 105 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10015] = { sid = 10015, path = "Scene/Senlin/prefabs/Senlin", name = "北区郊外", items = { 1001509001 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10016] = { sid = 10016, path = "Scene/Nanzhendongqushuniu/prefabs/Nanzhendongqushuniu", name = "北区枢纽", items = { 1001609001, 1001609002, 104 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [30001] = { sid = 30001, path = "Scene/Jianghu/prefabs/Jianghu", name = "生存试炼", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10018] = { sid = 10018, path = "Scene/Zhucheng_southeast_corner/prefabs/Zhucheng_southeast_corner", name = "时光秘境", items = { 1001809001 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [30011] = { sid = 30011, path = "Scene/Nanzhendongqushuniu/prefabs/Nanzhendongqushuniu", name = "意志试炼", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10020] = { sid = 10020, path = "Scene/Zhucheng_southeast_corner/prefabs/Zhucheng_southeast_corner", name = "组队副本", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10021] = { sid = 10021, path = "Scene/Nanzhendongqushuniu/prefabs/Nanzhendongqushuniu", name = "黑色诺亚", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10022] = { sid = 10022, path = "Scene/Dixiagedouchang/prefabs/Dixiagedouchang", name = "研发室", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10023] = { sid = 10023, path = "Scene/Senlin/prefabs/Senlin", name = "森林", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10024] = { sid = 10024, path = "Scene/Nanzhendongqushuniu/prefabs/Nanzhendongqushuniu", name = "复古东区枢纽", items = { 1002409501, 1002409502 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10025] = { sid = 10025, path = "Scene/Zhucheng_southeast_corner/prefabs/Zhucheng_southeast_corner", name = "复古东区中央城", items = { 1002509501, 1002509502, 1002509503 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10026] = { sid = 10026, path = "Scene/Nanzhendongqushuniu/prefabs/Nanzhendongqushuniu", name = "通道", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10027] = { sid = 10027, path = "Scene/Dixiagedouchang/prefabs/Dixiagedouchang", name = "混乱时空", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10028] = { sid = 10028, path = "Scene/Nanzhendongqushuniu/prefabs/Nanzhendongqushuniu", name = "挑战者大厅", items = { 1002809001, 1002809002 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10029] = { sid = 10029, path = "Scene/Dixiagedouchang/prefabs/Dixiagedouchang", name = "超时空竞技场", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10030] = { sid = 10030, path = "Scene/Nanzhendongqu/prefabs/nanzhendongquzhuzhaiqu_01", name = "复古东区住宅区", items = { 1003009501 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [10031] = { sid = 10031, path = "Scene/Nanzhendongqujiaowai/prefabs/Nanzhendongqujiaowai", name = "复古东区郊外", items = { 1003109501 }, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20101] = { sid = 20101, path = "Scene/Nanzhendongqu/prefabs/nanzhendongquzhuzhaiqu_01", name = "故事推图-东区住宅区-1个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20102] = { sid = 20102, path = "Scene/Nanzhendongqu/prefabs/nanzhendongquzhuzhaiqu_01", name = "故事推图-东区住宅区-2个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20103] = { sid = 20103, path = "Scene/Nanzhendongqu/prefabs/nanzhendongquzhuzhaiqu_01", name = "故事推图-东区住宅区-3个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20201] = { sid = 20201, path = "Scene/Nanzhendongquguangchang/prefabs/Shangyeguangchang", name = "故事推图-东区广场-1个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20202] = { sid = 20202, path = "Scene/Nanzhendongquguangchang/prefabs/Shangyeguangchang", name = "故事推图-东区广场-2个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20203] = { sid = 20203, path = "Scene/Nanzhendongquguangchang/prefabs/Shangyeguangchang", name = "故事推图-东区广场-3个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20301] = { sid = 20301, path = "Scene/Senlin/prefabs/Senlin", name = "故事推图-森林-1个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20302] = { sid = 20302, path = "Scene/Senlin/prefabs/Senlin", name = "故事推图-森林-2个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20303] = { sid = 20303, path = "Scene/Senlin/prefabs/Senlin", name = "故事推图-森林-3个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20401] = { sid = 20401, path = "Scene/Nanzhendongqushuniu/prefabs/Nanzhendongqushuniu", name = "故事推图-通道-1个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20402] = { sid = 20402, path = "Scene/Nanzhendongqushuniu/prefabs/Nanzhendongqushuniu", name = "故事推图-通道-2个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20403] = { sid = 20403, path = "Scene/Nanzhendongqushuniu/prefabs/Nanzhendongqushuniu", name = "故事推图-通道-3个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20501] = { sid = 20501, path = "Scene/Dixiagedouchang/prefabs/Dixiagedouchang", name = "故事推图-研发室-1个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20502] = { sid = 20502, path = "Scene/Dixiagedouchang/prefabs/Dixiagedouchang", name = "故事推图-研发室-2个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20503] = { sid = 20503, path = "Scene/Dixiagedouchang/prefabs/Dixiagedouchang", name = "故事推图-研发室-3个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20601] = { sid = 20601, path = "Scene/Dixiagedouchang/prefabs/Dixiagedouchang", name = "故事推图-混乱时空-1个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20602] = { sid = 20602, path = "Scene/Dixiagedouchang/prefabs/Dixiagedouchang", name = "故事推图-混乱时空-2个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20603] = { sid = 20603, path = "Scene/Dixiagedouchang/prefabs/Dixiagedouchang", name = "故事推图-混乱时空-3个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20701] = { sid = 20701, path = "Scene/Nanzhendongqushuniu/prefabs/Nanzhendongqushuniu", name = "故事推图-黑色诺亚-1个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20702] = { sid = 20702, path = "Scene/Nanzhendongqushuniu/prefabs/Nanzhendongqushuniu", name = "故事推图-黑色诺亚-2个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20703] = { sid = 20703, path = "Scene/Nanzhendongqushuniu/prefabs/Nanzhendongqushuniu", name = "故事推图-黑色诺亚-3个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20801] = { sid = 20801, path = "Scene/Battle_Streetscape/prefabs/Battle_Streetscape", name = "故事推图-东区城郊-1个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20802] = { sid = 20802, path = "Scene/Battle_Streetscape/prefabs/Battle_Streetscape", name = "故事推图-东区城郊-2个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20803] = { sid = 20803, path = "Scene/Battle_Streetscape/prefabs/Battle_Streetscape", name = "故事推图-东区城郊-3个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20901] = { sid = 20901, path = "Scene/Zhucheng_southeast_corner/prefabs/Zhucheng_southeast_corner", name = "故事推图-东区中央城-1个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20902] = { sid = 20902, path = "Scene/Zhucheng_southeast_corner/prefabs/Zhucheng_southeast_corner", name = "故事推图-东区中央城-2个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [20903] = { sid = 20903, path = "Scene/Zhucheng_southeast_corner/prefabs/Zhucheng_southeast_corner", name = "故事推图-东区中央城-3个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [21001] = { sid = 21001, path = "Scene/Dixiagedouchang/prefabs/Dixiagedouchang", name = "故事推图-擂台-1个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [21002] = { sid = 21002, path = "Scene/Dixiagedouchang/prefabs/Dixiagedouchang", name = "故事推图-擂台-2个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [21003] = { sid = 21003, path = "Scene/Dixiagedouchang/prefabs/Dixiagedouchang", name = "故事推图-擂台-3个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [21101] = { sid = 21101, path = "Scene/Jisitading/prefabs/Jisitading", name = "故事推图-吉斯塔顶-1个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [21102] = { sid = 21102, path = "Scene/Jisitading/prefabs/Jisitading", name = "故事推图-吉斯塔顶-2个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [21103] = { sid = 21103, path = "Scene/Jisitading/prefabs/Jisitading", name = "故事推图-吉斯塔顶-3个怪", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [30003] = { sid = 30003, path = "Scene/Jianghu/prefabs/Jianghu", name = "生存试炼", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [30004] = { sid = 30004, path = "Scene/Jianghu/prefabs/Jianghu", name = "生存试炼", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [30005] = { sid = 30005, path = "Scene/Jianghu/prefabs/Jianghu", name = "生存试炼", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [30006] = { sid = 30006, path = "Scene/Jianghu/prefabs/Jianghu", name = "生存试炼", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [30012] = { sid = 30012, path = "Scene/Dixiagedouchang/prefabs/Dixiagedouchang", name = "意志试炼白虎", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [30013] = { sid = 30013, path = "Scene/Jianghu/prefabs/Jianghu", name = "意志试炼朱雀", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },
    [30014] = { sid = 30014, path = "Scene/Nanzhendongquguangchang/prefabs/Shangyeguangchang", name = "意志试炼玄武", items = {}, View = "", BgMusics = { 1, 2, 3 }, NotSync = 0, NearbySid = { 1 } },

})