

return _G.ConstClass("AudioConfig",{
    [1] = { Sid = 1, Path = "Audio/BGM/BGM_DengLu", Sync = false, LoopInterval = 10, TransitionTime = 2 },
    [2] = { Sid = 2, Path = "Audio/BGM/BGM_ChangJing_1", Sync = false, LoopInterval = 10, TransitionTime = 2 },
    [3] = { Sid = 3, Path = "Audio/BGM/BGM_FuBen_1", Sync = false, LoopInterval = 10, TransitionTime = 2 },
    [20] = { Sid = 20, Path = "Audio/TongYong/JieMianDaKai", Sync = false, LoopInterval = -1, TransitionTime = 0 },
    [21] = { Sid = 21, Path = "Audio/TongYong/JiaMianGuanBi", Sync = false, LoopInterval = -1, TransitionTime = 0 },
    [22] = { Sid = 22, Path = "Audio/TongYong/WuXiaoCaoZuo", Sync = false, LoopInterval = -1, TransitionTime = 0 },
    [23] = { Sid = 23, Path = "Audio/SimpleButton", Sync = false, LoopInterval = -1, TransitionTime = 0 },
    [50] = { Sid = 50, Path = "Audio/GongNeng/XinXiaoXi", Sync = false, LoopInterval = -1, TransitionTime = 0 },
    [51] = { Sid = 51, Path = "Audio/GongNeng/XinYouJian", Sync = false, LoopInterval = -1, TransitionTime = 0 },
    [52] = { Sid = 52, Path = "Audio/GongNeng/ChuanSong", Sync = false, LoopInterval = -1, TransitionTime = 0 },
    [53] = { Sid = 53, Path = "Audio/GongNeng/BaoXiang", Sync = false, LoopInterval = -1, TransitionTime = 0 },
    [101] = { Sid = 101, Path = "Audio/BGM/Mutually Exclusive Dichotomy", Sync = false, LoopInterval = 10, TransitionTime = 2 },
    [102] = { Sid = 102, Path = "Audio/BGM/Cutting Edge", Sync = false, LoopInterval = 10, TransitionTime = 2 },
    [103] = { Sid = 103, Path = "Audio/BGM/ESAKA!!", Sync = false, LoopInterval = 10, TransitionTime = 2 },
    [104] = { Sid = 104, Path = "Audio/BGM/KD-0079+", Sync = false, LoopInterval = 10, TransitionTime = 2 },
    [105] = { Sid = 105, Path = "Audio/BGM/nanjiu", Sync = false, LoopInterval = 10, TransitionTime = 2 },
    [106] = { Sid = 106, Path = "Audio/BGM/Seoul Town", Sync = false, LoopInterval = 10, TransitionTime = 2 },
    [107] = { Sid = 107, Path = "Audio/BGM/Windy Day", Sync = false, LoopInterval = 10, TransitionTime = 2 },
    [108] = { Sid = 108, Path = "Audio/BGM/Mutually Exclusive Dichotomy", Sync = false, LoopInterval = -1, TransitionTime = 0 },
    [109] = { Sid = 109, Path = "Audio/BGM/Cutting Edge", Sync = false, LoopInterval = -1, TransitionTime = 0 },
    [110] = { Sid = 110, Path = "Audio/BGM/ESAKA!!", Sync = false, LoopInterval = -1, TransitionTime = 0 },
    [111] = { Sid = 111, Path = "Audio/BGM/KD-0079+", Sync = false, LoopInterval = -1, TransitionTime = 0 },
    [112] = { Sid = 112, Path = "Audio/BGM/nanjiu", Sync = false, LoopInterval = -1, TransitionTime = 0 },
    [113] = { Sid = 113, Path = "Audio/BGM/Seoul Town", Sync = false, LoopInterval = -1, TransitionTime = 0 },
    [114] = { Sid = 114, Path = "Audio/BGM/Windy Day", Sync = false, LoopInterval = -1, TransitionTime = 0 },
    [115] = { Sid = 115, Path = "Audio/BGM/xingge3", Sync = false, LoopInterval = 10, TransitionTime = 2 },

})