

return _G.ConstClass("LanguagePackage",{
    GameName = { Key = "GameName", CN = "全明星觉醒" },
    Common_System = { Key = "Common_System", CN = "系统" },
    Common_SystemNotice = { Key = "Common_SystemNotice", CN = "系统公告" },
    Common_Sure = { Key = "Common_Sure", CN = "确定" },
    Common_Sure_1 = { Key = "Common_Sure_1", CN = "确认" },
    Common_Sure_2 = { Key = "Common_Sure_2", CN = "同意" },
    Common_Cancel = { Key = "Common_Cancel", CN = "取消" },
    Common_Cancel_1 = { Key = "Common_Cancel_1", CN = "撤销" },
    Common_Cancel_2 = { Key = "Common_Cancel_2", CN = "不同意" },
    Common_Cancel_3 = { Key = "Common_Cancel_3", CN = "再想想" },
    Common_Open = { Key = "Common_Open", CN = "打开" },
    Common_Close = { Key = "Common_Close", CN = "关闭" },
    Common_Close_Any = { Key = "Common_Close_Any", CN = "点击空白区域继续游戏" },
    Common_Any_Close = { Key = "Common_Any_Close", CN = "点击任意空白区域关闭" },
    Common_Title = { Key = "Common_Title", CN = "提示" },
    Common_Title_1 = { Key = "Common_Title_1", CN = "温馨提示" },
    Common_Title_2 = { Key = "Common_Title_2", CN = "系统提示" },
    Common_Title_3 = { Key = "Common_Title_3", CN = "放弃确认" },
    Common_Title_4 = { Key = "Common_Title_4", CN = "替换确认" },
    Login_HaveRole = { Key = "Login_HaveRole", CN = "已有伙伴" },
    Login_BestServer = { Key = "Login_BestServer", CN = "推荐服务器" },
    Login_UnSelectServer = { Key = "Login_UnSelectServer", CN = "请选择服务器" },
    Login_NameCantNil = { Key = "Login_NameCantNil", CN = "用户名不能为空" },
    Login_BtnLogin = { Key = "Login_BtnLogin", CN = "登录游戏" },
    Login_ServerArea = { Key = "Login_ServerArea", CN = "[%s区] %s" },
    Login_ServerArea_1 = { Key = "Login_ServerArea_1", CN = "%s-%s区" },
    Login_CurServer = { Key = "Login_CurServer", CN = "%s区" },
    Login_BtnNotice = { Key = "Login_BtnNotice", CN = "公告" },
    Login_NoticeNull = { Key = "Login_NoticeNull", CN = "暂无公告" },
    NoticeDesc = { Key = "NoticeDesc", CN = "1~欢迎~欢迎您来到《%s》，祝您游戏愉快！~1~1474387200~0" },
    ServerState_Hot = { Key = "ServerState_Hot", CN = "爆满" },
    ServerState_Busy = { Key = "ServerState_Busy", CN = "繁忙" },
    ServerState_Open = { Key = "ServerState_Open", CN = "流畅" },
    ServerState_Close = { Key = "ServerState_Close", CN = "维护" },
    ServerState_New = { Key = "ServerState_New", CN = "新服" },
    RealNameRegister_00 = { Key = "RealNameRegister_00", CN = "根据国家新闻出版署发布的《关于防止未成年人沉迷网络游戏的通知》您需要进行实名制方可继续进行游戏。点击“确定”前往实名制认证。" },
    RealNameRegister_01 = { Key = "RealNameRegister_01", CN = "游戏实名登记" },
    RealNameRegister_02 = { Key = "RealNameRegister_02", CN = "亲爱的玩家，根据国家相关法规规定，请尽快完成实名登记，拥有完整游戏体验。" },
    RealNameRegister_03 = { Key = "RealNameRegister_03", CN = "姓名" },
    RealNameRegister_04 = { Key = "RealNameRegister_04", CN = "国家/地区" },
    RealNameRegister_05 = { Key = "RealNameRegister_05", CN = "中国大陆" },
    RealNameRegister_06 = { Key = "RealNameRegister_06", CN = "证件号" },
    RealNameRegister_07 = { Key = "RealNameRegister_07", CN = "请填写真实姓名" },
    RealNameRegister_08 = { Key = "RealNameRegister_08", CN = "请填写真实有效身份证号" },
    RealNameRegister_09 = { Key = "RealNameRegister_09", CN = "确认登记" },
    System_ExitGame_Desc = { Key = "System_ExitGame_Desc", CN = "未来的航海王，您要提前结束您的新世界航路之旅吗？" },
    System_Net_BreakOff = { Key = "System_Net_BreakOff", CN = "网络连接断开，是否重新连接?" },
    System_Net_Timeout = { Key = "System_Net_Timeout", CN = "通讯超时，请确认网络通畅后重试！" },
    System_Error_Version = { Key = "System_Error_Version", CN = "游戏版本已更新，请下载后再试." },
    System_Warning = { Key = "System_Warning", CN = "抵制不良游戏 拒绝盗版游戏 注意自我保护 谨防受骗上当 适度游戏益脑 沉迷游戏伤身 合理安排时间 享受健康生活" },
    System_Maintenance = { Key = "System_Maintenance", CN = "服务器正在维护中，请关注游戏公告并稍后再试" }
})