---@class LanguagePackage_Item
---@field public Key string @字段
---@field public CN string @语言描述


---@class LanguagePackage
---@field public GameName  LanguagePackage_Item @全明星觉醒
---@field public Common_System  LanguagePackage_Item @系统
---@field public Common_SystemNotice  LanguagePackage_Item @系统公告
---@field public Common_Sure  LanguagePackage_Item @确定
---@field public Common_Sure_1  LanguagePackage_Item @确认
---@field public Common_Sure_2  LanguagePackage_Item @同意
---@field public Common_Cancel  LanguagePackage_Item @取消
---@field public Common_Cancel_1  LanguagePackage_Item @撤销
---@field public Common_Cancel_2  LanguagePackage_Item @不同意
---@field public Common_Cancel_3  LanguagePackage_Item @再想想
---@field public Common_Open  LanguagePackage_Item @打开
---@field public Common_Close  LanguagePackage_Item @关闭
---@field public Common_Close_Any  LanguagePackage_Item @点击空白区域继续游戏
---@field public Common_Any_Close  LanguagePackage_Item @点击任意空白区域关闭
---@field public Common_Title  LanguagePackage_Item @提示
---@field public Common_Title_1  LanguagePackage_Item @温馨提示
---@field public Common_Title_2  LanguagePackage_Item @系统提示
---@field public Common_Title_3  LanguagePackage_Item @放弃确认
---@field public Common_Title_4  LanguagePackage_Item @替换确认
---@field public Login_HaveRole  LanguagePackage_Item @已有伙伴
---@field public Login_BestServer  LanguagePackage_Item @推荐服务器
---@field public Login_UnSelectServer  LanguagePackage_Item @请选择服务器
---@field public Login_NameCantNil  LanguagePackage_Item @用户名不能为空
---@field public Login_BtnLogin  LanguagePackage_Item @登录游戏
---@field public Login_ServerArea  LanguagePackage_Item @[%s区] %s
---@field public Login_ServerArea_1  LanguagePackage_Item @%s-%s区
---@field public Login_CurServer  LanguagePackage_Item @%s区
---@field public Login_BtnNotice  LanguagePackage_Item @公告
---@field public Login_NoticeNull  LanguagePackage_Item @暂无公告
---@field public NoticeDesc  LanguagePackage_Item @1~欢迎~欢迎您来到《%s》，祝您游戏愉快！~1~1474387200~0
---@field public ServerState_Hot  LanguagePackage_Item @爆满
---@field public ServerState_Busy  LanguagePackage_Item @繁忙
---@field public ServerState_Open  LanguagePackage_Item @流畅
---@field public ServerState_Close  LanguagePackage_Item @维护
---@field public ServerState_New  LanguagePackage_Item @新服
---@field public RealNameRegister_00  LanguagePackage_Item @根据国家新闻出版署发布的《关于防止未成年人沉迷网络游戏的通知》您需要进行实名制方可继续进行游戏。点击“确定”前往实名制认证。
---@field public RealNameRegister_01  LanguagePackage_Item @游戏实名登记
---@field public RealNameRegister_02  LanguagePackage_Item @亲爱的玩家，根据国家相关法规规定，请尽快完成实名登记，拥有完整游戏体验。
---@field public RealNameRegister_03  LanguagePackage_Item @姓名
---@field public RealNameRegister_04  LanguagePackage_Item @国家/地区
---@field public RealNameRegister_05  LanguagePackage_Item @中国大陆
---@field public RealNameRegister_06  LanguagePackage_Item @证件号
---@field public RealNameRegister_07  LanguagePackage_Item @请填写真实姓名
---@field public RealNameRegister_08  LanguagePackage_Item @请填写真实有效身份证号
---@field public RealNameRegister_09  LanguagePackage_Item @确认登记
---@field public System_ExitGame_Desc  LanguagePackage_Item @未来的航海王，您要提前结束您的新世界航路之旅吗？
---@field public System_Net_BreakOff  LanguagePackage_Item @网络连接断开，是否重新连接?
---@field public System_Net_Timeout  LanguagePackage_Item @通讯超时，请确认网络通畅后重试！
---@field public System_Error_Version  LanguagePackage_Item @游戏版本已更新，请下载后再试.
---@field public System_Warning  LanguagePackage_Item @抵制不良游戏 拒绝盗版游戏 注意自我保护 谨防受骗上当 适度游戏益脑 沉迷游戏伤身 合理安排时间 享受健康生活
---@field public System_Maintenance  LanguagePackage_Item @服务器正在维护中，请关注游戏公告并稍后再试
