---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wyx.
--- DateTime: 2019/11/5 14:11
--- 和Unity交互的模块全部在这里初始化,尽量不要调整加载顺序
local CS = _G.CS

_G.Mathf = require "Mathf"
_G.Vector2 = require "Vector2"
_G.Vector3 = require "Vector3"
_G.Vector4 = require "Vector4"
_G.Quaternion = require "Quaternion"
_G.Color = require "Color"
_G.Ray = require "Ray"
_G.Bounds = require "Bounds"
_G.RaycastHit = require "RaycastHit"
_G.Touch = require "Touch"
_G.Plane = require "Plane"
_G.Time = require "Time"
_G.Object = require "Object"

--region unity相关静态方法的全局引用

---@type UnityEngine.GameObject
_G.GameObject = CS.UnityEngine.GameObject
---@type UnityEngine.RectTransform
_G.RectTransform = CS.UnityEngine.RectTransform
---@type UnityEngine.Canvas
_G.Canvas = CS.UnityEngine.Canvas
---@type UnityEngine.Renderer
_G.Renderer = CS.UnityEngine.Renderer
---@type UnityEngine.ParticleSystem
_G.ParticleSystem = CS.UnityEngine.ParticleSystem
---@type UnityEngine.UI.GraphicRaycaster
_G.GraphicRaycaster = CS.UnityEngine.UI.GraphicRaycaster
---@type UnityEngine.Random
_G.Random = CS.UnityEngine.Random
---@type UnityEngine.Input
_G.Input = CS.UnityEngine.Input
---@type UnityEngine.Application
_G.Application = CS.UnityEngine.Application
---@type UnityEngine.SphereCollider
_G.SphereCollider = CS.UnityEngine.SphereCollider
---@type UnityEngine.CapsuleCollider
_G.CapsuleCollider = CS.UnityEngine.CapsuleCollider
---@type UnityEngine.BoxCollider
_G.BoxCollider = CS.UnityEngine.BoxCollider
---@type UnityEngine.Collider
_G.Collider = CS.UnityEngine.Collider
---@type UnityEngine.Rigidbody
--_G.Rigidbody = CS.UnityEngine.Rigidbody
---@type UnityEngine.AI.NavMeshAgent
_G.NavMeshAgent = CS.UnityEngine.AI.NavMeshAgent
---@type UnityEngine.AI.OffMeshLink
_G.OffMeshLink = CS.UnityEngine.AI.OffMeshLink
---@type UnityEngine.UI.LayoutRebuilder
--_G.LayoutRebuilder = CS.UnityEngine.UI.LayoutRebuilder
--endregion

---region 自定义类
---@type XLuaManager
_G.CSXLuaManager = CS.XLuaManager.Instance
---@type GameManager
--_G.CSGameManager = CS.GameManager.Instance
---@type UIModel
_G.CSUIModel = CS.UIModel.Inst
---@type TextUtils
--_G.CSTextUtils = CS.TextUtils
---endregion

-- function _G.DestroyImmediate(obj)
--     CS.UnityEngine.Object.DestroyImmediate(obj.gameObject)
-- end

-- function _G.DestroyObject(obj)
--     CS.UnityEngine.Object.Destroy(obj.gameObject)
-- end

-- function _G.DestroyCompent(obj)
--     CS.UnityEngine.Object.Destroy(obj)
-- end

-- function _G.DestroyObjectDelyTime(obj, time)
--     CS.UnityEngine.Object.Destroy(obj.gameObject, time)
-- end

-- ---实例化GameObject
-- ---@param obj UnityEngine.GameObject GameObject
-- ---@param parent UnityEngine.Transform 父节点
-- ---@return UnityEngine.GameObject GameObject
-- function _G.InstantiateObject(obj, parent)
--     if parent then
--         return CS.UnityEngine.Object.Instantiate(obj.gameObject, parent)
--     else
--         return CS.UnityEngine.Object.Instantiate(obj.gameObject)
--     end
-- end

-- ---查找游戏对象
-- ---说明：1.GameObject只能查找到active的物体
-- ---　　　2.如果name指定路径，则按路径查找；否则递归查找，直到查找到第一个符合条件的GameObject或者返回null
-- ---@param name string 对象名字
-- ---@return UnityEngine.GameObject 游戏对象
-- function _G.FindObject(name)
--     return CS.UnityEngine.GameObject.Find(name)
-- end

-- ---对list进行排序
-- ---@generic T
-- ---@param list T[]
-- ---@param sortFun (fun(item:T):number) | "function(item) end"
-- ---默认降序排序
-- function _G.SortList(list, sortFun)
--     local listData = {}

--     for i = 1, #list do
--         local item = list[i]
--         listData[i] = {
--             item = item,
--             sorts = {sortFun(item)} --参数检查?
--         }
--     end

--     table.sort(listData, function(a, b)
--         for i = 1, #a.sorts do
--             local as = a.sorts[i]
--             local bs = b.sorts[i]
--             if (as ~= bs) then
--                 return as > bs
--             end
--         end
--         return false
--     end)

--     for i = 1, #listData do
--         list[i] = listData[i].item
--     end
-- end
